# Trading Configuration
trading:
  default_symbol: AAPL
  position_size: 100
  max_positions: 5
  risk_per_trade: 0.02

# Market Data
market_data:
  cache_dir: data/cache
  update_interval: 60
  symbols:
    - AAPL
    - MSFT
    - GOOGL

# Strategy Parameters
strategy:
  sma_crossover:
    short_window: 20
    long_window: 50
  rsi:
    period: 14
    overbought: 70
    oversold: 30

# Logging
logging:
  level: INFO
  file: logs/trading.log
  max_size: 10485760  # 10MB
  backup_count: 5

# Database
database:
  path: data/db/trading.db

# Performance
performance:
  max_daily_loss: 0.05
  max_position_size: 100000
  max_open_trades: 10 